### ISSUE TITLE
Database credentials exposed publicly

### ISSUE THREAD

**Issue by Plazmaz** [Catilina/Dashboard#1]
Hello! I'd like to bring to your attention that your database credentials are exposed publicly through https://raw.githubusercontent.com/Catilina/Dashboard/936ab5d01dc87ef8f78ac95fba2fcac97c20ea21/api/index.js
Please note that this data cannot be removed from github. A commit removing this information would not delete the link above. The only solution to protect your data is to change your passwords where relevant. I _strongly_ suggest you look at https://help.github.com/articles/remove-sensitive-data/ and change your password.

**Comment by chrisdarling** [comment]
DB credentials are no longer exposed and password has changed. Thank you!
